// Generated by LispyScript v1.0.0
var express = require("express");
var bodyParser = require("body-parser");
var cors = require("cors");
var AWS = require("aws-sdk");
var jo = require("jpeg-autorotate");
var multer = require("multer");
var s3ToStudentCode = (function(accessKeyId,secretAccessKey) {
    return new AWS.S3({
			accessKeyId,
			secretAccessKey,
			region: "us-east-1"});
})("AKIAJYUDOK5G26RRCJJA","eXQ2hWLubY/p2wzkWEXpwf342Meoo5+tX8fefUHi");
var studentCodeBucket = "www.gegirlstech.com";
var app = express();
var port = (process.env.PORT || 9000);
((port === 9000) ?
    app.use(cors()) :
    app.use(cors({origin: "http://www.gegirlstech.com"})));
app.use(bodyParser.json({limit: '10mb'}));
app.use(bodyParser.urlencoded({ extended: false, limit: '10mb' }));
var saveCodeOptions = function(body) {
    return (function(pcNumber,code,month) {
        return (function(key) {
            return {	Bucket: studentCodeBucket,
				Key: key,
				Body: code};
        })(["classes/",month,"/studentCode/app",pcNumber,".js"].join(''));
    })((body).pcNumber,(body).code,(body).month);
};
var createPutObjectCallback = function(res) {
    return function(err,data) {
        return (function() {
            console.log(err,data);
            return (err ?
                (res.status(500)).send({status: 500, message: err, type:'internal'}) :
                (res.status(200)).send({status:200, data}));
        })();
    };
};
app.post("/savecode",function(req,res) {
    return (function(options,callback) {
        return (function() {
            console.log((req).body);
            return s3ToStudentCode.putObject(options,callback);
        })();
    })(saveCodeOptions((req).body),createPutObjectCallback(res));
});
var uploadpicOptions = function(body) {
    return (function(month,pcNumber,filetype,regex) {
        return (function(Key,originalBuffer) {
            return { Bucket: studentCodeBucket, 
				Key,
				ContentType: filetype, 
				CacheControl: "no-cache",
				Body: originalBuffer};
        })(["classes/",month,"/studentPics/studentPic",pcNumber].join(''),new Buffer(body.data_uri.replace(regex,""),"base64"));
    })((body).month,(body).pcNumber,(body).filetype,new RegExp("^data:image\\/\\w+;base64,"));
};
app.post("/uploadpic",(multer()).single('file'),function(req,res) {
    return (function() {
        console.log("got a post at /uploadpic");
        return (function(options) {
            return jo.rotate((options).Body,{},function(error,buffer,orientation) {
                return (function(bufferToPut) {
                    return (function(updatedOptions) {
                        return s3ToStudentCode.putObject(options,createPutObjectCallback(res));
                    })(Object.assign,{},options,{Body: bufferToPut});
                })((error ?
                    (options).Body :
                    buffer));
            });
        })(uploadpicOptions((req).body));
    })();
});
app.listen(port,function() {
    return console.log("I am listening on port ",port,"!");
});
